#!/usr/bin/python3

# System Imports
from os import getpid
from pathlib import PurePath

# Local Imports
from includes.python_logger import create_logger


def main():
    logger = create_logger(PurePath(__file__).stem)
    logger.info(f"Successfully executed base finalize script as pid: {getpid()}")


if __name__ == "__main__":
    main()
